#!/usr/bin/env python

import sys, os
from ConfigParser import *
from ymapClass import *

def main():
	cfgFile = os.path.expanduser('~/.ymap.cfg')
	profileFile = os.path.expanduser('~/.ymap-profile')

	if os.path.exists(cfgFile) == False:
		print "%s not found" % cfgFile
		return False

	profileName = 'default'
	
	if os.path.exists(profileFile):
		try:
			f = open(profileFile, 'r')
			p = f.readline()
			if p != '':
				profileName = p
		finally:
			f.close

	print "using profile: %s" % profileName

	if len(sys.argv) == 1:
		print "known commands as frist arg:"
		print "  profile         (list profiles)"
		print "  profile [name]  (select profile)"
		print "  list            (fetch file list)"
		print "  get [num]       (fetch file)"
		print "  put [filename]  (upload file)"
		return True
	
	cmd = sys.argv[1]
	
	if cmd == 'profile' and len(sys.argv) > 2:
		try:
			f = open(profileFile, 'w')
			f.write(sys.argv[2])
			print "switched to profile %s" % sys.argv[2]
		finally:
			f.close
		
		return True

	knownCommands = ('get', 'put', 'profile', 'list')
	twoArgsCommands = ('get', 'put')

	if cmd in twoArgsCommands and len(sys.argv) <= 2:
		print "arg2 missing"
		return False
	
	if cmd not in knownCommands:
		print "unknown command: %s" % sys.argv[1]
		return False

	try:
		config = ConfigParser()
		config.read(cfgFile)
		
		if cmd == 'profile':
			print "sections: %s" % config.sections()
			return True

		if profileName not in config.sections():
			print "unknown profile: %s" % profileName
			return False

		server = config.get(profileName, 'Server')
		port = config.getint(profileName, 'Port')
		ssl = config.getboolean(profileName, 'SSL')
		user = config.get(profileName, 'User')
		password = config.get(profileName, 'Password')
		folder = config.get(profileName, 'Folder')
	except:
		print "could not read ymap.cfg"
		return False
	
	print "Connecting..."
	i = ymap()
	if i.connect(server, port, ssl, user, password, folder) == False:
		return False
	print "Connected."

	if cmd == 'list':
		print "Fetching message list..."
		i.list()

	elif cmd == 'put':
		i.put(sys.argv[2])

	elif cmd == 'get':
		i.get(sys.argv[2], os.getcwd())

	i.disconnect()
	return False


if __name__ == "__main__":
	if main():
		sys.exit(0)
	else:
		sys.exit(1)

